### PR TITLE
UI: setting's logic

### PR DESCRIPTION
**Pull request by royalmo**

### CODE REVIEW

**Review by royalmo — COMMENTED** [review]
From here on, just `settings.js` should be modified. The internal preference policy should be thought wisely.

**Review by royalmo — COMMENTED** [review]
- [x] Implement `encrypt`/`decrypt` functions.
- [ ] When `settings.set` changes current sync value, copy settings from one place to another. **Do not copy tokens nor sync settings!!**

**Review by royalmo — COMMENTED** [review]
All ready for @FlyingKoala01 's review!

**Review by FlyingKoala01 — APPROVED** [review]
Good Work! :D

**Review by FlyingKoala01 — APPROVED** [review]
Maybe now will work?

**Pull request merged**
