### PR TITLE
Edit files in `escriny.epsem.upc.edu`

### PR DESCRIPTION
**Pull request by royalmo**
At the end of the branch, files can be edited in escriny's website, without the need to download subversion and the entire repository.

For the moment, work is still in progress.

We need to add SVNJS still to the extension files.

### CODE REVIEW

**Comment by royalmo** [comment]
This is what happens when commiting an existing file or a new file.
```
22:56:21 ==> OPTIONS request success
22:56:21 ==> Acitivity path is: /svn/itic-copilot-test/!svn/act/
22:56:21 ==> PROPFIND https://escriny.epsem.upc.edu/svn/itic-copilot-test:207 Multi-Status
22:56:22 ==> MKACTIVITY request success
22:56:22 ==> Activity /svn/itic-copilot-test/!svn/act/lgaqhh3b-zkbk-f1ar-1grn-wa9yuzpaqhh4
22:56:22 ==> MKACTIVITY INFO END
22:56:22 ==> CHECKOUT /svn/itic-copilot-test/!svn/vcc/default done!
22:56:22 ==> PROPPATCH success
22:56:22 ==> CHECKOUT /svn/itic-copilot-test/!svn/ver/2/ done!
22:56:22 ==> PUT /svn/itic-copilot-test/!svn/wrk/lgaqhh3b-zkbk-f1ar-1grn-wa9yuzpaqhh4/ fail
22:56:22 ==> 409 Conflict
22:56:22 ==> PUT INFO END
22:56:22 ==> DELETE /svn/itic-copilot-test/!svn/act/lgaqhh3b-zkbk-f1ar-1grn-wa9yuzpaqhh4 done
```

**Comment by royalmo** [comment]
When adding file in a subfolder:
```
23:30:12 ==> OPTIONS request success
23:30:12 ==> Acitivity path is: /svn/itic-copilot-test/!svn/act/
23:30:12 ==> PROPFIND https://escriny.epsem.upc.edu/svn/itic-copilot-test:207 Multi-Status
23:30:13 ==> MKACTIVITY request success
23:30:13 ==> Activity /svn/itic-copilot-test/!svn/act/rvfsbymy-qrzf-c3wn-jqcw-uoc1c97kx7jp
23:30:13 ==> MKACTIVITY INFO END
23:30:13 ==> CHECKOUT /svn/itic-copilot-test/!svn/vcc/default done!
23:30:13 ==> PROPPATCH success
23:30:13 ==> CHECKOUT /svn/itic-copilot-test/!svn/ver/2//hola/byee.rst fail
23:30:13 ==> 404 Not Found
23:30:13 ==> CHECKOUT INFO END
23:30:13 ==> DELETE /svn/itic-copilot-test/!svn/act/rvfsbymy-qrzf-c3wn-jqcw-uoc1c97kx7jp done
```

**Comment by royalmo** [comment]
After crying a little bit, i have found some documentation!

Here it is: https://svnbook.red-bean.com/en/1.7/svn-book.html

Be careful with Property Setting and image files, they cannot be edited! (https://svnbook.red-bean.com/en/1.7/svn-book.html#svn.advanced.props.auto)

Found docs concerning webDAV: http://www.webdav.org/specs/rfc4918.html

Found docs concerning DeltaV: http://www.webdav.org/specs/rfc3523.html

**Comment by royalmo** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

it works :)

image

**Review by FlyingKoala01 — APPROVED** [review]
Sweeeeeet :3 🐨

**Review by FlyingKoala01 — APPROVED** [review]
Awesome Work!

**Pull request merged**
